### ISSUE TITLE
get the string content of a row

### ISSUE THREAD

**Issue by greg0ire** [halilim/xml-iterator#5]
I am trying to figure out if I could use this library to find top-elements of an xml document in a memory-efficient way, leaving the parsing of each element to another library ?

Basically, I have a `mysldump --xml` output that generates an xml file with node that have attributes. I would like to get the content of each top level `row` element, **as a string, not as an array** with this library, and feed it to the xml parser of my choice. This way I could have the best of both worlds. Is there an option I could set so that `XmlIterator#current()` returns a string and not an array ?

**Comment by sagikazarmark** [comment]
IMO it is out of scope. The current feature set is straightforward, no need for mixing it up. My plan is to create a generic xml iterator interface (if needed at all) and see if we can create iterators which return the desired structure. Either an array or any object.

**Comment by greg0ire** [comment]
Oh ok, sorry for the noise then.

**Comment by sagikazarmark** [comment]
No problem, I don't think it is noise. I just think the way I see it is more generic than you propose. Do you disagree?

**Comment by greg0ire** [comment]
For me the there are two responsabilities when parsing the xml: 

1. finding the rows
2. parsing each element

I think there should be only one implementation for 1. and several for 2. , and IMO the implementation for 1. (the xml iterator) should have a dependency on an implementation for 2. 

I think you are proposing to have several implementations for 1. : One that is simple and deals with flat arrays, and another that would be able to do more complex things. Did I understand correctly or not ?

**Comment by greg0ire** [comment]
I also think the iterator should be able to feed the xml element parser unaltered string representations of each row. Basically, it should give the unaltered contents of what is found between `<row>` and `</row>` in a mysqldump file

**Comment by sagikazarmark** [comment]
Hm, basically the two are the same. The difference is in the level of dependencies. By having an iterator and a parser you have two levels. By having the both in one you have only one.

You can create an abstraction which contains the iteration logic and use that in the specific implementations. The reason I think this solution is better is that we are talking about iterators, thus you need to iterate over the elements. It is better to return the preprocessed element rather than processing it during the iteration.

From this point whether the iterator returns a string, an array or an object doesn't really matter. Use the one based on your needs.

**Comment by sagikazarmark** [comment]
Anyway, checking the source code, you can make the iterator return a simple xml element. @halilim can you confirm that?

**Comment by greg0ire** [comment]
> It is better to return the preprocessed element rather than processing it during the iteration.

The problem is having a memory-efficient iterator that also is able to parse an element correctly (keeping the attributes, for instance).

If it is good enough for your dump the iterator should return the pre-processed element. If it is not good enough, then it should call the xml parser to do the job.

I pushed [here](https://github.com/greg0ire/data-import-extra/commit/84de9ee903150ddf1fff542d87e0ef9d62d19746) an example of how to achieve that with an optional dependency. What do you think ?

**Comment by sagikazarmark** [comment]
I can't see why it is more efficient than having the "processing" logic in the iterator. Actually the extra (conditional) method call (processing the result in the reader returned from the iterator) adds an overhead.

An iterator returning the desired structure does not add any overhead (besides the conversion).

**Comment by greg0ire** [comment]
It is not more efficient, it just avoids code duplication. Not having to write the iteration part for each file format you have is what I'm trying to gain here.

**Comment by sagikazarmark** [comment]
> You can create an abstraction which contains the iteration logic and use that in the specific implementations.

``` php
abstract class/trait XmlIteratorContainingReadingLogic {}

class XmlIteratorReturningSimpleXmlElement extends XmlIteratorContainingReadingLogic {}
```

This is just one path.

**Comment by greg0ire** [comment]
Since I read [this article](http://ocramius.github.io/blog/when-to-declare-classes-final/), I'm quite reluctant to use extension to provide a way to extend software. I think composition is better, because there is no SRP violation with it. Here there are two responsabilities, so there really should be two classes.

**Comment by sagikazarmark** [comment]
Actually no, it is one responsibility as long as you don't require special things (like add a letter 'a' in front of all values). You are iterating over data which can have one or two general structure.

One thing to keep in mind: memory efficiency. That beats any kind of acronyms  (SRP, ASD, WTF, BBQ, etc) commonly (badly) recognized as a synonym decent software development.

Also, I realized that this library itself supports returning both an array and a simple xml element. That should be more than enough.

**Comment by greg0ire** [comment]
IMHO memory efficiency is relevant for the top level parsing only : imported elements are not big, they are numerous.
And complex parsing capabilites are relevant for the elements, not for the top level parsing, than only needs to be able to recognize top level elements (an easy task).

The change I propose let us do things both ways : 
- your way if there is no dependency
- my way if there is one

So it is a good design, because it should keep us both happy even if we disagree on how to parse elements.

> That beats any kind of acronyms (SRP, ASD, WTF, BBQ, etc) commonly (badly) recognized as a synonym decent software development.

This was funny, but not very nice. I was not trying to impress you with an acronym, I know you probably know the SRP more than enough. If you won't admit there are two responsibilities, and accept the change I propose, then I guess we should ask someone else to settle this (@Baachi maybe ?). Because I feel the discussion will not be going nowhere if we start throwing sarcasms at each other.

**Comment by sagikazarmark** [comment]
> This was funny, but not very nice.

Sorry, it wasn't my intention to be sarcastic. Neither was to throw anything at you. I see the potential in your solution, I just think that there is no need to over-generalize this. There are two or three viable use cases which we can cover with simple solutions without exposing an extension point.

Also, since I realized this iterator is capable of what we are trying to achieve, we can close this issue for now. However there is an extension point here as well (namely the options array) which I don't really like.

**Comment by sagikazarmark** [comment]
BTW extension point: if you are able to pass a processor into the iterator, you are risking that any other implementations depending on the iterator gets an object, which returns a data structure it cannot recognize.

**Comment by sagikazarmark** [comment]
Hm, it seems that your proposed solution is not related to the iterator at all, but the XmlReader implementation. Am I right?

**Comment by greg0ire** [comment]
> Am I right?

Maybe . It is related to the `XmlElementReader` implementation. What I am proposing is : in the case the xmliterator is not good enough to parse elements, then inject an `XmlElementReaderInterface` implementation that will do that.

**Comment by sagikazarmark** [comment]
That is what I am afraid of that it could cause an unwanted extension point, since in theory the XmlElementReader should be able to return any type of data: array or object. You cannot write an XmlReader which handles any type of them, but a specific for each one.

**Comment by greg0ire** [comment]
I think we should simply specify in the interface that an XmlElementReader should always return an array, because only array work with the other objects (for instance, the `FilterInterface` has a method `filter` with an array type hint).

**Comment by sagikazarmark** [comment]
I guess it's time to move this discussion to ddeboer/data-import#138

**Comment by halilim** [comment]
@sagikazarmark yes, you get a `SimpleXMLElement` if you instantiate it like this:

    $it = new XmlIterator(
        "http://api.example.com/products.xml",
        "product",
        [
            "asArray" => false
        ]
    );

If `asArray` is true (default), the element is converted to an array.

**Comment by Baachi** [comment]
Guys keep calm, its just a implementation. Xml is a really generic format and i don't think there is a way to convert xml to array in a generic way. (Correct me if i'm wrong).

This library have a great way to have a generic way and keep the code simple. To you discussions about software design, keep in mind, code should be simple as possible. With the possibilty to get an `SimpleXMLElement` object instead of an array, you have access to attributes.

@greg0ire If i understand you correctly, you want to import an mysql dump which is generate as xml. Why not just create an class which wraps this class or extend this class. We are in OOP so this shouldn't be a problem.

**Comment by greg0ire** [comment]
@Baachi : because I believe that, even there might be no generic way to transform an xml file in an array, people will always have to write this conversion step if they want to use the library.

So what I am saying is : 

1. we are sure there will be the need to find rows in an XML file
2. we are sure there will be the need to convert each xml elements

I think we should have a simple implementation for 1. , a simple implementation for 2. and make sure that anyone can override 1. but still use 2. easily and vice versa. Most of the time, the implementation for 1. should be good enough for everyone, simply because most people have their rows at the top-level of the xml document. But since the structure of xml elements will vary a lot, 2. will often be overriden by people.

I have one import from a mysqldump file, and another import from a file in a non-standard format, that looks like this:

```xml
<orders>
<order id="14227">
    <user uuid="9fd623d20cfc4eb487a6f3a81269ecd0"/>
    <vat>19.6000</vat>
    <transactions>
      <transaction id="14227">
        <amount>4.1722</amount>
        <comment>paybox-4b3d441575997664761423</comment>
      </transaction>
    </transactions>
    <orderlines>
      <orderline id="14404">
        <paidPrice>4.1722</paidPrice>
        <price>4.1722</price>
        <quantity>1</quantity>
        <product id="1171" type="rent">
          <price vat="20.0000" value="3.3250"/>
        </product>
      </orderline>
    </orderlines>
    <creationDate>2010-01-01 01:38:51</creationDate>
    <status>validated</status>
  </order>
  <order id="14228">
    <user uuid="0be733f2dacf558203d86dbf80ffef2a"/>
    <vat>19.6000</vat>
    <transactions>
      <transaction id="14228">
        <amount>3.3361</amount>
        <comment>paybox-4b3d6138bd13a641722778</comment>
      </transaction>
    </transactions>
    <orderlines>
      <orderline id="14405">
        <paidPrice>3.3361</paidPrice>
        <price>3.3361</price>
        <quantity>1</quantity>
        <product id="925" type="rent">
          <price vat="20.0000" value="3.3250"/>
        </product>
      </orderline>
    </orderlines>
    <creationDate>2010-01-01 03:43:39</creationDate>
    <status>validated</status>
  </order>
</orders>
```
As you can see, the same implementation of 1. can be used in both cases, but for 2. I really need a parser that can give attributes back.

The implementations of 2. differ because in the case of mysqldump, I need to do the following special treatment : 

```
    public function read(\SimpleXmlElement $parentElement)
    {
        $row = array();

        foreach ($parentElement as $element) {
            $attributes = $element->attributes('http://www.w3.org/2001/XMLSchema-instance');

            $row[(string) $element['name']] =
                (isset($attributes['nil']) && $attributes['nil']) ?
                    null:
                    (string) $element;
        }

        return $row;
    }
```
